/// > 


namespace Test02 {

    @test
    def test01(): Result[Unit, String] & Impure = 
        use Result.flatMap;
        let* json1 = JsonProcessing/JsonObject.readFile("e://coding//flix//json-processing//data//floc1.json");
        let* json2 = JsonProcessing/JsonObject.readFile("e://coding//flix//json-processing//data//floc2.json");
        let patch = JsonProcessing/JsonPatch.createJsonObjectDiff(json1, json2);
        println("A patch...");
        patch |> println;
        Ok()

}
